### ISSUE TITLE
how to set maximum number of character per  tag

### ISSUE THREAD

**Issue by NishaLodhi** [xvendo/tagit#1]
I am using xvendo/tagit  to store skills .but I found that there is no limit of character of a tag which may cause failure of my project, you can see the image.I want to aplly character limit on each skills

![image](https://cloud.githubusercontent.com/assets/24477134/25779423/2f43b586-3335-11e7-8efb-8ea833c93c0b.png)

**Comment by xvendo** [comment]
This is possible!

Please refer to the this link: https://github.com/aehlke/tag-it

tagLimit (integer)

Limits the total number of tags that can be entered at once. Note that if you use this option with preloaded data, it may truncate the number of preloaded tags. Set to null for unlimited tags. See the onTagLimitExceeded callback for customizing this behavior.

Defaults to null.
