### ISSUE TITLE
tag is not creating in mobile

### ISSUE THREAD

**Issue by NishaLodhi** [xvendo/tagit#2]
('#id').tagit();
is working fine on the desktop.But when I am trying the same package on the phone it is not creating the tag in the mobile(using comma, spacebar). but when I click somewhere else on the phone screen after writing something in the tag box then it creating a tag,

**Comment by xvendo** [comment]
In that case just try It if possible on a different phone. It's possible that the library doesn't support any browser system (android, ios, etc.). 

Please refer to the original github of tagit().
